<?php

global $SDK_VER;
global $UCLOUD_PROXY_SUFFIX;
global $UCLOUD_PUBLIC_KEY;
global $UCLOUD_PRIVATE_KEY;

$SDK_VER = "1.0.9";


$UCLOUD_PROXY_SUFFIX = env('UCLOUD_PROXY_SUFFIX','.hk.ufileos.com');
$UCLOUD_PUBLIC_KEY = env('UCLOUD_PUBLIC_KEY','3fgt0OVVLpdHrehdsRYfovD4OkU6zgkfW15FHaXbka');
$UCLOUD_PRIVATE_KEY = env('UCLOUD_PRIVATE_KEY','EddW6s5y0L8Am2ezZ3vK606fbJs9W9iH7K9TwzYxMblqGHw7nrVzpU4FqRoTThod6');
